backend:
  name: git-gateway
  repo: HotMessPaint/darrelbelvin.github.io
  branch: master
  site_domain: darrelbelvin.github.io

local_backend: true

media_folder: "content/blog/{{slug}}"

site_url: https://hotmesspaint.netlify.com/
