backend:
  name: git-gateway
  repo: HotMessPaint/darrelbelvin.github.io
  branch: master
  site_domain: darrelbelvin.github.io

media_folder: "content"

site_url: https://https://hotmesspaint.netlify.com/

collections:
  - name: page
    label: Page
    folder: "blog"
    create: true
    fields:
      - { name: title, label: title }
      - { name: date, label: Date, widget: datetime }
      - { name: thumbnail, label: Title }
      - { name: description, label: Description }
      - { name: tags, label: Tags }
      - { name: body, label: Body, widget: markdown }
